
import { Outfit } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import Providers from "./providers";
const outfit = Outfit({
  subsets: ["latin"],weight:["400","500","600","700"]
});


export const metadata = {
  title: "My Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
       <Providers>{children}</Providers>
         
            
          
          
      
      </body>
    </html>
  );
}
